export const questions = [
  {
    type: "multiple",
    difficulty: "hard",
    category: "Entertainment: Music",
    question: "Which of these songs is not by Tatsuro Yamashita?",
    correct_answer: "Lucky Lady Feel So Good ",
    incorrect_answers: [
      "Merry-Go Round",
      "Let&#039;s Dance Baby",
      "Love Talkin&#039;",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Entertainment: Books",
    question:
      "In which classic novel by Mark Twain did a beggar and Prince of Wales switch clothes, and learn about social class inequality?",
    correct_answer: "The Prince and the Pauper",
    incorrect_answers: [
      "Hamlet",
      "Wealthy Boy and the Schmuck",
      "A Modern Twain Story",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "General Knowledge",
    question: "Which one of these Swedish companies was founded in 1943?",
    correct_answer: "IKEA",
    incorrect_answers: ["H &amp; M", "Lindex", "Clas Ohlson"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Entertainment: Video Games",
    question: "What block in Minecraft has the highest blast resistance?",
    correct_answer: "Barrier",
    incorrect_answers: ["Obsidian", "Bedrock", "Block of Diamond"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Vehicles",
    question:
      "Which car tire manufacturer is famous for its &quot;Eagle&quot; brand of tires, and is the official tire supplier of NASCAR?",
    correct_answer: "Goodyear",
    incorrect_answers: ["Pirelli", "Bridgestone", "Michelin"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "How fast is USB 3.1 Gen 2 theoretically?",
    correct_answer: "10 Gb/s",
    incorrect_answers: ["5 Gb/s", "8 Gb/s", "1 Gb/s"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Entertainment: Video Games",
    question:
      "In the game Pok&eacute;mon Conquest, how many kingdoms make up the region of Ransei?",
    correct_answer: "17",
    incorrect_answers: ["18", "15", "16"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Celebrities",
    question: "Which television show has Dan Gheesling been on?",
    correct_answer: "Big Brother",
    incorrect_answers: ["Jeopardy", "Survivor", "The Bachelor"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What do you study if you are studying entomology?",
    correct_answer: "Insects",
    incorrect_answers: ["Humans", "the Brain", "Fish"],
  },
];
