export enum ActionType {
  RESET_STORE = "reset-store",
  SET_SINGLE_PLAYER_MODE = "set-single-player-mode",
  SET_MULTI_PLAYER_MODE = "set-multi-player-mode",
  SELECT_NUMBER_OF_PLAYERS = "select-number-of-players",
  SET_IS_FORM_VALID = "set-is-form-valid",
  ADD_USER_NAME = "add-user-name",
  CLEAR_USERS_ARRAY = "clear-users-array",
  SET_QUIZ_MODE = "set-quiz-mode",
  SET_IS_QUIZ_MODE_SET = "set-is-quiz-mode-set",
  SET_PLAYER_QUIZ_DATA = "set-player-quiz-data",
  RESET_USER_CATEGORIES = "reset-user-categories",
  SET_QUESTIONS_SHOULD_LOAD = "questions-should-load",
  SET_QUESTIONS_FOR_EACH_USER = "set-questions-for-each-user",
  SET_ACTUAL_USER_ID = "set-actual-user-id",
  COUNT_SCORE = "count-score",
}
